version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:5000"
  
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=tennet